<!DOCTYPE html>
<!--[if IE 6]> <html id="ie ie67  ie6" dir="ltr" lang="en-US"> <![endif]-->
<!--[if IE 7]> <html id="ie ie67  ie7" dir="ltr" lang="en-US"> <![endif]-->
<!--[if IE 8]> <html id="ie ie678 ie8" dir="ltr" lang="en-US"> <![endif]-->
<!--[if !(IE 6) | !(IE 7) | !(IE 8)  ]><!--> <html dir="ltr" lang="en-US"> <!--<![endif]-->
	<head>
		<title>Crossings Community Church</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<link rel="stylesheet" href="css/screen.css" type="text/css" media="screen" />
		<link rel="stylesheet" href="css/print.css" type="text/css" media="print" />
	</head>
	<body class="doctrinal">
		<div id="container">
			<div id="header">
				<a href="http://crossingscommunity.com/">
				</a>
			</div>
			<div id="nav">
				<ul>
					<li id="about" class="selected"><a href="about.php">About Crossings</a></li>
					<li id="sermons"><a href="/sermons/">Sermons</a></li>
					<li id="sermons"><a href="songs.php">Songs</a></li>
					<li id="critter"><a href="critter-crossings.php">Critter Crossings</a></li>
					<li id="members"><a href="members.php">Members</a></li>
					<li id="week"><a href="restofweek.php">Rest of Week</a></li>
					<li id="contact"><a href="contact.php">Contact Us</a></li>
				</ul>
			</div>
			<div id="sub-nav">
				<ul>
					<li id="vision"><a href="about.php">Vision</a></li>
					<li id="docstate" class="selected"><a href="doctrinal-statement.php">Doctrinal Statement</a></li>
					<li id="sunday"><a href="sundays.php">Sunday Mornings</a></li>
					<li id="stones"><a href="stones.php">Stones</a></li>
				</ul>
			</div>
			<div id="content">
				<h2>Doctrinal Statement<br />Crossings Community Church<br />Abridged</h2>
				<p><strong>We believe</strong> in God, the all-powerful, Creator of the universe. <strong>We believe</strong> in the Triune God, one in essence, attributes, and nature, yet three in Persons-Father, Son, and Holy Spirit (Matthew 3:16-17; John 1:29-34; 14:16-17, 26; 15:26; 16:7-15; Ephesians 1:3-14; 4:4-6; II Corinthians 13:14; I John 5:1-12). <strong>We believe</strong> that God is a knowable God, and that He has revealed Himself through natural revelation in the creation (Romans 1:20-His eternal power and divine nature; Psalm 104:24-God's wisdom and power in the creation), and through special revelation, primarily through His Holy Word (John 16:13-16; Acts 1:1-2; II Peter 1:20-21; II Timothy 3:16), and ultimately in His Son Jesus Christ (John 14:9; Hebrews 1:1-2; Matthew 11:27).</p>
				<p><strong>We believe</strong> that man, as a result of the initial sin of Adam, is totally depraved from conception (Psalm 51:5; 58:3). Man sins in deed because of his sinful bent or disposition. The very mind of man is corrupted, and his core disposition is to be rebellious towards God (Jeremiah 17:1-5; Ephesians 2:3). <strong>We believe</strong> that man is a free moral agent in that no one coerces him to do good or evil. However, man, apart from God, does not and cannot choose God because of His depravity and bondage to sin. Man, apart from God, loves the darkness (John 3:19-20; 6:39, 44). He is totally alienated from God and is spiritually dead (Ephesians 2:1). As a result of this "deadness" he cannot participate in his "resurrection," anymore then a corpse might attempt to reanimate itself (Romans 8:7).</p>
				<p><strong>We believe</strong> that Jesus Christ is God (John 1:1; Romans 1:3-4; Colossians 1:13). As God, He was as to His existence the only man in human history whose life did not begin with His birth. <strong>We believe</strong> that Jesus Christ pre-existed all things, that He is eternal and has no beginning (Isaiah 44:5-6; Micah 5:2; Matthew 2:46; John 1:1, 15, 30). <strong>We believe</strong> that Jesus Christ carried out the Father's plan of creation and created all living creatures, inanimate objects, and even time itself (John 1:1-3; Colossians 1:16; Hebrews 1:2). <strong>We believe</strong> that Jesus Christ was born to the virgin Mary (Matthew 1:16, 18, 25; Luke 1:34, 35-37). <strong>We believe</strong> that Christ was born of Mary, but was conceived by the Holy Spirit and not Joseph (Genesis 3:15; Matthew 1:20; Luke 1:30-35). This is of the utmost importance, in that the virgin birth both insures that Christ is God, and that He is qualified to be our perfect, sinless redeemer (Psalm 49: 7-8; John 1:1; Romans 5:12; Hebrews 2:9; 10:10-17). <strong>We believe</strong> that Jesus Christ died, was buried, and rose again on the third day (I Corinthians 15:1-4). <strong>We believe</strong> that this work is the only basis for salvation from sin and from guilt (Matthew 10:28; Acts 4:12; Romans 3:21-25; 5:9; I Corinthians 15:3; Hebrews 7:26-27; 9:11-14; I John 2:1-2). <strong>We believe</strong> that it is a substitutionary payment for our sin (Matthew 20:28), and that it was planned by God and prophesied by the Scriptures (Genesis 3:15; Psalm 22:40; Isaiah 53; Matthew 26:54-56; Luke 24:25-27; Hebrews 10:5-9). <strong>We believe</strong> that only through faith in Jesus Christ, on the basis of His gracious redemptive work, is there salvation from sin (Ephesians 2:8-9). <strong>We believe</strong> in the actual, physical death of Jesus Christ, and that He rose from the dead, "on the third day according to the Scriptures, and that He appeared to Cephas, then to the twelve. After that He appeared to more than five hundred brethren at one time. (I Corinthians 15:4-6)." <strong>We believe</strong> that Christ is now exalted, equal in position with the Father over all creation (Philippians 2:10-11; Revelation 5:11-14). <strong>We believe</strong> that He reigns over His church, as He is the head of it (Colossians 1:18). <strong>We believe</strong> that Christ has authority over Satan and all spirit beings, as well as over all creation (Matthew 28:18; Ephesians 1:21-22; Colossians 1:14-15; I John 4:4).</p>
				<p><strong>We believe</strong> that salvation, from beginning to end, is a work of God. Apart from this work, man could never attain salvation because of his deadness in sin (Ephesians 2:1-3). <strong>We believe</strong> that the plan of salvation began in eternity past and consisted of three elements-foreknowledge, predestination, and election. Foreknowledge, regards a certain (meaning it is sure), intimate, selective, and personal knowledge of something (Acts 2:23; Romans 8:29; I Peter 1:2). <strong>We believe</strong> that God foreknew His children, and therefore predestined and elected these ones to be His (Acts 13:48; Ephesians 1:5). Predestination speaks to God having ordained the destiny of some to be His sons and daughters and to spend eternity with Him. "For whom He foreknew, He also predestined to become conformed to the image of His Son (Romans 8:29)." This He did out of the kind intention of His will, not based on anything we would have or could have done, but by His grace (Ephesians 1:5; 2:8-9). <strong>We believe</strong> that a person must be regenerated in order to place his/her faith in Jesus Christ and be saved. Jesus referred to regeneration as being "born again (John 3:1-12)." With respect to man's role in his salvation, <strong>We believe</strong> that repentance and faith occur after regeneration. However, <strong>We believe</strong> that faith is the immediate result of regeneration (Luke 3:9-14; John 3:36; Acts 11:18-23; 20:21; Philippians 3:9; I Thessalonians 1:9). The sinner recognizes his sin and it's offensiveness to a holy God, feels the guilt of that sin, and makes a decision to turn from it to live for God. Upon realizing his need of a Savior, the sinner places his faith in Christ, a trusting that only Jesus can save him from his sin and from the judgment and wrath of God. This faith, true faith, always produces fruit, and a desire to serve Christ and to live for Him alone. <strong>We believe</strong> that these ones can never lose their salvation, and will on the Day of Judgment stand blameless before God (John 6:39-40; 10:25-29; Romans 8:29-39).</p>
				<p><strong>We believe</strong> that the converted are baptized with the Holy Spirit at the time of conversion (I Corinthians 12:13; Galatians 2:20; 3:26; I John 5:11-12). The agent of Spirit baptism is Jesus (Matthew 3:11; I Corinthians 12:13). <strong>We believe</strong> that positionally, as a result of our being baptized in the Spirit, we become members of the body of Christ ( I Corinthians 12:12, 27), and become the children of God, prepared for an eternity with Him (Galatians 3:26-27). <strong>We believe</strong> that the Holy Spirit indwells believers, and only believers, at the moment of salvation ( John 14:15-17; Romans 8:9-11; Ephesians 1:13; II Timothy 1:14; Titus 3:4-7). <strong>We believe</strong> that the indwelling of the Holy Spirit is permanent (John 14:16; Ephesians 4:30), and is a gift given by God to His children (Acts 11:17; I Corinthians 2:12; II Corinthians 5:5). <strong>We believe</strong> the indwelling of the Holy Spirit is proof of a true conversion and occurs in every Christian (Romans 8:9-10; I Corinthians 2:14; 6:19). <strong>We believe</strong> that the believer becomes a temple, a holy place, once indwelt with the Spirit (I Corinthians 6:19-20). <strong>We believe</strong> that the Holy Spirit is a pledge and a seal, showing God's ownership of a person and guaranteeing the completion of their salvation (Ephesians 1:13-14; II Corinthians 1:22; 5:5). <strong>We believe</strong> that the Holy Spirit sanctifies the believer throughout the course of his/her life (Romans 6:12-23; 8:12-17; Galatians 5:16-24; II Thessalonians 2:13). The believer is changed more and more into the image of Christ by means of prayer, the Word of God, and fellowship with the body of Christ in conjunction with the indwelling Spirit (Romans 8:29-30; Ephesians 1:15-23; 3:14-21; Hebrews 10:24-25; I Peter 1:22-2:3; 21; I John 2:27-28; 3:23-24).</p>
				<p><strong>We believe</strong> that the written Word of God is inspired or "God-breathed" (II Timothy 3:16). <strong>We believe</strong> that the Scriptures originated with God, being "breathed-out" or coming directly from His mouth, by His effort. <strong>We believe</strong> that the Scriptures are inerrant; that is that they are completely without fault, misstatement or contradiction of any kind (Mark 14:21). Therefore, <strong>We believe</strong> that they are authoritative and trustworthy in every respect. Jesus and the apostles attested to their authoritativeness and therefore their inerrancy as well (Matthew 21:42; I Corinthians 14:37-38; Galatians 1:24; Ephesians 2:20; I Thessalonians 5:27; II Peter 1:20-21; 3:15-16). <strong>We believe</strong> that the Scriptures are sufficient to equip the man of God for every good work, in every contingency of life (II Timothy 3:1-4:5; II Peter 1:3).</p>
				<p><strong>We believe</strong> in the church of God, built by the Lord Jesus Christ (Matthew 16:18). <strong>We believe</strong> that the building of the church was and is dependent on the work of redemption accomplished by Christ, as well as certain works of the Holy Spirit, and began on the day of Pentecost (Matthew 16:18; John 14:20; Acts 1:4-5; 20:28; I Corinthians 12:13; Ephesians 1:21-23; 2:22; 4:7-11, 15; Colossians 1:27; 2:10). <strong>We believe</strong> that the completion of the church is certain, and will culminate in the Second Coming of Christ (Acts 15:14). <strong>We believe</strong> that the church is presently being completed, built by the Lord's continually gathering people out of all nations (I Kings 6:7; Acts 15:14; I Peter 2:5). At His return, Christ will remove the church from the earth by means of resurrection and translation (I Corinthians 15:51; I Thessalonians 1:10; 4:13). Finally, <strong>We believe</strong> that the church will be united forever with her Head who is Christ the Lord (Ephesians 5:25; Revelation 19:6).</p>
				<p><strong>We believe</strong> that there are two sacraments given to be performed by the church today. The first, baptism, is a physical sign of the spiritual reality of the new birth (Romans 6). Therefore, only the saved, and those old enough to understand baptism's significance, should be baptized. We are commanded to baptize believers by Jesus Christ Himself. This baptism is to be done in the name of the Father, the Son, and the Holy Spirit (Matthew 28:18-19). The Lord's supper is, like baptism, prescribed by Jesus Christ Himself, and is a remembrance of Him and His work. <strong>We believe</strong> it is designed to remind the church of its relationship to Him, thereby protecting it's unity in Him. <strong>We believe</strong> it is to be taken with certain things in mind. We are to remember Christ's suffering on the cross (I Corinthians 11:24-31); we are to keep the church in mind to remind us that we are one in Him (I Corinthians 10:16-17); and we are to await eagerly Christ's coming kingdom (Mark 14:25; I Corinthians 11:25).</p>
				<p><strong>We believe</strong> that we now live in what Jesus referred to as "the last days" or end times (Romans 13:11-12; I Corinthians 10:11). <strong>We believe</strong> in the imminent and triumphant return of Jesus Christ to the earth ( Acts 1:9-11; I Thessalonians 1:9-10; 4:16-18; II Thessalonians 4:7-8; Revelation 1:7). <strong>We believe</strong> that at the time of Christ's return there will be a rapture of the church (I Corinthians 15:51-53; I Thessalonians 4:16-17). At this point, <strong>We believe</strong> that the bodies of both the saved and unsaved will be resurrected (Daniel 12:2-3; Acts 24:15; I Corinthians 15:35-49; II Corinthians 5:1-4; II Peter 3:15; Revelation 20:11-15). All true believers (both alive and dead) will be taken up from this earth to be with Christ (John 5:28-29; I Thessalonians 4:16-17; I Corinthians 15:51-52). Ultimately, they will dwell in the new heavens and the new earth, following the destruction of the old (Revelation 21). <strong>We believe</strong> that the unbelieving (both dead and alive) will be called to judgment, and will be ultimately cast into the lake of fire for an eternity apart from God (Revelation 20:11-15). <strong>We believe</strong> that heaven and hell are real places, one a place of great torment for the unbelieving, where there will be weeping and gnashing of teeth, and one where believers will remain in the presence of the Lord forever (Matthew 5:22; 10:28; Luke 12:5; 16:19-31; John 11:25-26; Romans 8:1; Hebrews 9:15).</p>
			</div>
		</div>
		<?php include($_SERVER['DOCUMENT_ROOT'] . '/inc/_footer.php'); ?>
	</body>
</html>
